from ._index import dp
from .menu_catalog import dp
from .menu_settings import dp
from .menu_newsletter import dp
from .menu_users import dp
from .menu_support import dp
from .menu_payments import dp
from .menu_transactions import dp
from .menu_stats import dp